### ISSUE TITLE
Slack @references are rendered as <@UNIQUEID>

### ISSUE THREAD

**Issue by erikogan** [jimmycuadra/lita-karma#18]
When a user is referenced in a Slack message, it comes through in the body as  &lt;@UNIQUEID&gt;. This causes lita-karma to work inconsistently on Slack. 

Obviously, this can be fixed with a custom `term_pattern` to match it and a custom `term_normalizer` to look up the user. But I think the defaults should probably handle this case because it breaks the principle of least astonishment.

I’m going to dig into fixing it now.

**Comment by erikogan** [comment]
I was hoping to switch the `term_pattern` and `term_normalizer` at start up time, to keep the performance effect of this change down. But when the plugin is being configured `Lita.config.robot.adapter` is set to `:shell`.

Is there a better way to query the configured adapter at start up, or is this the timing problem it appears to be?

**Comment by jimmycuadra** [comment]
Are you using the latest Slack adapter? That type of special Slack formatting should be removed from messages before being received by the robot now. If you're on the latest version of the adapter, I'd consider it a hole in our coverage of special Slack formatting that should be removed.

**Comment by erikogan** [comment]
I installed it without specifying a version in the Gemfile, so I assume that means I’m running the latest released version. 

I can try running on the master branch on Github and see if it performs differently.

**Comment by erikogan** [comment]
That’s worse. It expands @mention to “@full name” with spaces, so in the case of karma it considers the last name the term: `@erik++` expands to `@Erik Ogan++`

But now that I know it’s a bug in the lita-slack adapter, I can open an issue over there.
