### ISSUE TITLE
Routes are added twice, at least during testing

### ISSUE THREAD

**Issue by directionless** [jimmycuadra/lita-karma#22]
Hi there! I'm looking at tweaking some behavior, and wanted to write test cases. But, something is amiss. Most of the tests fail, because the command is executed twice. Digging a bit, I see the routes are generated twice.

I suspect something has changed in the last 11 months since your travis run, because if I just fork this, travis produces the same errors for me, as I get on my local host.

Though I did need to update travis to work around a bug. https://github.com/directionless/lita-karma/commit/0b19d2e4c is the commit that does so.

https://travis-ci.org/directionless/lita-karma/builds/108911896 is my fork's failure. I don't think anything I did should cause that, and I suspect you'll see the same thing. https://github.com/directionless/lita-karma/commit/6983d3f is a simple rspec file

**Comment by directionless** [comment]
I might be wrong about the "added twice" being the problem -- I see two sets of writes in a redis monitor, and poking around with pry and monkey patching, I can see the two routes being called. But I'm not sure what happens to get them both registered.

**Comment by jimmycuadra** [comment]
Thanks for the report! This was due to [this change](https://twitter.com/travisci/status/680327961652899840) in Lita. It's fixed on master now.
